version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
